[package]
name = "tweed"
version = "0.1.0"
authors = ["Issac Trotts <issac.trotts@gmail.com>"]
edition = "2018"

[dependencies]
twitter-stream = "0.9"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sentiment = "0.1.1"
lazy_static = "1.4.0"

